// Generating the document side of the retrieval bridge.
//
// THE PROBLEM THIS SOLVES is query-document asymmetry, measured rather than
// assumed: on the 15 gate queries the corpus was embedded as bare ancient prose
// and the queries arrive as modern first-person sentences. Ephesians 2:8-10 —
// "not of yourselves… not of works" — sat at vector rank 6 for "faith is
// something I have to build myself", behind Hebrews 11, because nothing in its
// text resembles that sentence. Enrichment writes the missing half of the
// bridge: what this passage is about, and what somebody who needs it might
// actually be saying.
//
// Generated by a model, deliberately NOT curated by hand. A curated
// situation-to-passage lookup is a Phase 5 product feature and would contaminate
// this measurement — it would be answering the gate queries directly rather than
// improving retrieval.

import OpenAI from "openai";

import { env } from "../../config/env";
import { models } from "../../config/models";
import { logger } from "../../lib/logger";

/**
 * Bumped whenever the prompt or the output shape changes.
 *
 * A prompt change is as significant as a model change: it produces different
 * content from the same model, and without a version the backfill selector
 * ("enriched by a different model") would treat stale output as current and skip
 * it. Recorded per document alongside enrichmentModel.
 */
export const ENRICHMENT_VERSION = 2;

export const HANDLING_VALUES = ["open", "care", "on-request-only"] as const;
export type Handling = (typeof HANDLING_VALUES)[number];

const STAGE_SLUGS = [
  "pride-humility",
  "greed-generosity",
  "lust-pure-love",
  "envy-gratitude",
  "gluttony-temperance",
  "wrath-patience",
  "sloth-diligence",
] as const;

export interface PassageToEnrich {
  reference: string;
  text: string;
  authorName?: string;
  authorEra?: string;
  authorCircumstances?: string;
}

export interface PassageEnrichment {
  reference: string;
  summary: string;
  situations: string[];
  themes: string[];
  stageSlugs: string[];
  cautions: string[];
  handling: Handling;
}

export interface EnrichmentResult {
  enrichments: PassageEnrichment[];
  promptTokens: number;
  completionTokens: number;
}

const SYSTEM_PROMPT = `You prepare scripture passages for a retrieval system in a Christian app.

People arrive at this app describing their lives in ordinary modern words — "I
can't forgive my brother", "I have money but I'm still afraid", "faith is
something I have to build myself". Your job is to describe each passage so that
such a sentence can find it. You are building a bridge between how people talk
and what the text says.

For each passage produce:

summary
  ONE plain sentence saying what is happening in this passage. Concrete, not
  devotional. "Paul argues that salvation is a gift and not something earned by
  effort" — not "a beautiful reminder of grace".

situations
  3 to 6 things a PERSON MIGHT SAY, in the first person, present tense, in their
  own modern words, that this passage genuinely speaks to. Write what they would
  type into an app at 11pm, not a topic label.
    good: "I think I have to earn my way to God"
    good: "I have enough and I'm still anxious"
    bad:  "salvation by grace", "anxiety", "the doctrine of justification"
  Be honest. If a passage is a genealogy or a building specification, say so in
  the summary and give few or no situations rather than inventing pastoral
  relevance it does not have.

themes
  2 to 5 concise topical tags, lowercase.

stageSlugs
  Zero or more of exactly these seven:
    pride-humility, greed-generosity, lust-pure-love, envy-gratitude,
    gluttony-temperance, wrath-patience, sloth-diligence

  A STAGE TAG MEANS "THIS PASSAGE HELPS SOMEONE WORKING THROUGH THIS STAGE."
  IT DOES NOT MEAN "THIS PASSAGE IS ABOUT THIS STAGE'S TOPIC."

  This distinction is the whole point of the field. Topic and help often point in
  OPPOSITE directions:
    - Leviticus 20:5-18 is topically about sex. It is NOT a resource for someone
      cultivating pure love — it is a legal code of capital penalties, and it
      would land on such a person as condemnation. Correct answer: no stage.
    - Song of Solomon 4 is topically about desire. It is the WRONG thing to hand
      someone fighting compulsion — explicit erotic imagery is the opposite of
      what helps. Correct answer: no stage.
    - Colossians 3:5-14, by contrast, names anger and tells you what to put on
      instead. That HELPS someone in wrath → patience. Correct answer: tag it.

  Ask "would giving this to someone doing this work move them forward?" — not
  "does this passage mention this subject?"

  MOST PASSAGES SERVE NONE OF THEM. An empty list is the normal, correct answer.
  Do not force a stage onto a passage to fill the field.

cautions
  When would handing this passage to a struggling person be the WRONG thing to
  do? Think about who should NOT receive it.
    - texts prescribing punishment, death, or exclusion, given to someone
      already ashamed or self-condemning
    - promises of prosperity or rescue given to someone whose situation has not
      been rescued
    - rebukes given to someone being abused or grieving, where the rebuke lands
      on the victim
    - passages about a specific historical or ceremonial matter that read as
      personal instruction when they are not
  Empty is a legitimate answer for a plainly comforting or neutral text. Be
  specific about WHO and WHY, not generic.

handling
  Exactly one of: open | care | on-request-only

  This is an OPERATIONAL flag, not a judgement about the text's worth. It answers
  one question: may this passage be put in front of a struggling person who did
  not ask for it?

  open
    Fine to surface unprompted. THE LARGE MAJORITY OF SCRIPTURE IS THIS.
    Narrative, teaching, poetry, wisdom, most law, most prophecy, genealogy.
    Difficult subject matter alone does NOT move a passage off open — Job's
    despair, Lamentations' grief and Psalm 88's unrelieved darkness are all open,
    because meeting someone in that place is the point.

  care
    Surface it, but it needs framing before it lands well. A meaningful minority.
    Rebukes, warnings, judgement oracles, passages easily misread as blaming the
    person receiving them.

  on-request-only
    NEVER put in front of someone in distress who did not ask. RARE. Reserve it
    for: graphic violence and atrocity, sexual judgment texts and capital
    penalties for sexual acts, explicit erotic content, and curses or imprecation
    calling for harm.
    Leviticus 20:5-18 and Song of Solomon 4 are both on-request-only.

  Be honest rather than protective. Marking ordinary scripture as restricted
  makes the flag useless and hides the passages that genuinely need it.

Answer only about the text in front of you. Do not import doctrine the passage
does not state.`;

const RESPONSE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["passages"],
  properties: {
    passages: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "reference",
          "summary",
          "situations",
          "themes",
          "stageSlugs",
          "cautions",
          "handling",
        ],
        properties: {
          reference: { type: "string" },
          summary: { type: "string" },
          situations: { type: "array", items: { type: "string" } },
          themes: { type: "array", items: { type: "string" } },
          stageSlugs: {
            type: "array",
            items: { type: "string", enum: [...STAGE_SLUGS] },
          },
          cautions: { type: "array", items: { type: "string" } },
          handling: { type: "string", enum: [...HANDLING_VALUES] },
        },
      },
    },
  },
} as const;

let client: OpenAI | null = null;
function getClient(): OpenAI {
  if (!client) client = new OpenAI({ apiKey: env.OPENAI_API_KEY });
  return client;
}

const sleep = (ms: number): Promise<void> =>
  new Promise((resolve) => setTimeout(resolve, ms));

function isRetryable(error: unknown): boolean {
  const status = (error as { status?: number })?.status;
  return status === 429 || status === 408 || (status !== undefined && status >= 500);
}

/**
 * Enriches a batch of passages in one call.
 *
 * Batched because 4,102 individual calls is both slow and needlessly expensive
 * on the shared system prompt — but kept small, because a model asked to hold
 * twenty passages in mind at once starts blurring them together and the
 * situations drift toward the generic.
 */
export async function enrichBatch(
  passages: PassageToEnrich[],
  modelId: string = models.premise,
): Promise<EnrichmentResult> {
  if (passages.length === 0) {
    return { enrichments: [], promptTokens: 0, completionTokens: 0 };
  }

  const userContent = passages
    .map((passage, index) => {
      const context = passage.authorName
        ? `\nWriter: ${passage.authorName}${
            passage.authorEra ? ` (${passage.authorEra})` : ""
          }${
            passage.authorCircumstances
              ? `\nWhat was happening to them: ${passage.authorCircumstances}`
              : ""
          }`
        : "";

      return `--- PASSAGE ${index + 1} ---\nReference: ${passage.reference}${context}\nText: ${passage.text}`;
    })
    .join("\n\n");

  const maxAttempts = 5;

  for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
    try {
      const response = await getClient().chat.completions.create({
        model: modelId,
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          {
            role: "user",
            content: `Enrich these ${passages.length} passages. Return one entry per passage, in order, echoing the reference exactly.\n\n${userContent}`,
          },
        ],
        response_format: {
          type: "json_schema",
          json_schema: {
            name: "passage_enrichments",
            strict: true,
            schema: RESPONSE_SCHEMA,
          },
        },
        // Generous on purpose. These are REASONING models: they spend tokens
        // before emitting any visible output, and a budget sized for the answer
        // alone comes back as `finish_reason: "length"` with EMPTY content and
        // no error at all (see lib/errors.ts ReasoningBudgetExhaustedError).
        max_completion_tokens: 16_000,
      });

      const choice = response.choices[0];
      const content = choice?.message?.content ?? "";

      if (!content) {
        throw new Error(
          `Model "${modelId}" returned empty content (finish_reason=${choice?.finish_reason}). ` +
            "If this is 'length', the reasoning budget was consumed before any output.",
        );
      }

      const parsed = JSON.parse(content) as { passages: PassageEnrichment[] };

      return {
        enrichments: parsed.passages,
        promptTokens: response.usage?.prompt_tokens ?? 0,
        completionTokens: response.usage?.completion_tokens ?? 0,
      };
    } catch (error) {
      if (!isRetryable(error) || attempt === maxAttempts) throw error;
      const wait = 1000 * 2 ** (attempt - 1) + Math.floor(Math.random() * 250);
      logger.warn({ attempt, waitMs: wait }, "enrichment call failed, retrying");
      await sleep(wait);
    }
  }

  throw new Error("unreachable: enrichBatch exhausted its retry loop");
}

/**
 * The text that actually gets embedded for the enriched vector.
 *
 * Situations come FIRST and are repeated nowhere else, because they are the part
 * that resembles a user's query. Then the summary, then themes, then the passage
 * itself — the raw text stays in so the enriched vector never loses what the
 * passage literally says.
 */
export function buildEnrichedText(
  enrichment: Pick<PassageEnrichment, "summary" | "situations" | "themes">,
  reference: string,
  text: string,
): string {
  const parts = [
    enrichment.situations.join(" "),
    enrichment.summary,
    enrichment.themes.join(", "),
    reference,
    text,
  ];

  return parts.filter((part) => part && part.trim().length > 0).join("\n");
}

/**
 * USD per 1M tokens, for the run report only.
 *
 * Published prices at the time of the Phase 3 build. Token counts in the report
 * are exact and come from the API; the dollar figure is the estimate.
 */
const PRICING: Record<string, { input: number; output: number }> = {
  "gpt-5": { input: 1.25, output: 10 },
  "gpt-5-mini": { input: 0.25, output: 2 },
  "gpt-5-nano": { input: 0.05, output: 0.4 },
};

export function estimateEnrichmentCost(
  promptTokens: number,
  completionTokens: number,
  modelId: string = models.premise,
): number {
  const price = PRICING[modelId];
  if (!price) return Number.NaN;
  return (
    (promptTokens / 1_000_000) * price.input +
    (completionTokens / 1_000_000) * price.output
  );
}
