// ARCHITECTURE.md §6, `passages` — THE RETRIEVABLE UNIT.
//
// Embed passages, never individual verses. Verse-level embeddings retrieve badly
// and the product hands someone a passage to sit with, so the unit that gets
// vectorised has to be the unit that gets read.
//
// `texts` is keyed by translationId so one passage carries every translation of
// itself. That is what makes translations pluggable (§5): adding a licensed
// translation later writes new entries into this map instead of migrating the
// collection.

import mongoose, { Schema } from "mongoose";
import type { Document, Types } from "mongoose";

import { applyApiTransforms } from "./model-utils";

export interface PassageDocument extends Document<Types.ObjectId> {
  /** Human reference, e.g. "Ephesians 2:8-10". Canonical, book NAME not slug. */
  reference: string;
  bookSlug: string;
  authorId: Types.ObjectId | null;
  chapter: number;
  startVerse: number;
  endVerse: number;
  /**
   * Chapter of the LAST verse.
   *
   * Extension beyond ARCHITECTURE.md §6, which lists a single `chapter`. Real
   * pericopes cross chapter boundaries — Matthew 9:35-10:4 is one sending
   * narrative, and the chapter break lands mid-thought — so a single chapter
   * field either forbids those units or silently truncates them. Defaults to
   * `chapter`, so the common single-chapter case is unaffected.
   */
  endChapter: number;
  /** translationId (as a string) -> the passage's text in that translation. */
  texts: Map<string, string>;
  themes: string[];
  stageSlugs: string[];
  situations: string[];
  /**
   * A note about the TEXT itself, distinct from a note about its author.
   *
   * John 7:53-8:11 is absent from the earliest manuscripts of John. An app that
   * hands someone a passage to sit with should say so rather than let them find
   * out from somewhere less careful — the same reasoning as
   * authors.attributionNote.
   */
  textualNote?: string;
  /**
   * Plain text of the passage in the DEFAULT translation, for keyword search.
   *
   * Denormalised deliberately. `texts` is a Map keyed by translationId, and
   * Mongo cannot build a text index over a Map's values — so hybrid retrieval
   * would have no keyword half at all without a flat field to index. Written by
   * segmentation, so it never drifts from `texts`.
   */
  searchText?: string;

  // ---- Enrichment (Phase 3 fix 1) ------------------------------------------
  //
  // Generated by a model, not curated by hand. The problem being solved is
  // query-document asymmetry: people arrive with modern first-person sentences
  // ("I think I have to earn my way to God") and the corpus is ancient prose.
  // Nothing in the raw text of Ephesians 2:8-10 looks like that sentence, which
  // is why it lost to Hebrews 11 on the raw embedding.
  /** One plain sentence: what is happening here. */
  summary?: string;
  /**
   * When this passage would be the WRONG thing to hand someone.
   *
   * Retrieval has a harm surface and Phase 6's safety gate sits in front of
   * Abigail, not in front of the retriever — see docs/RETRIEVAL-HARM.md. Stored
   * now, acted on in Phase 6.
   */
  cautions?: string[];
  /**
   * May this passage be put in front of a struggling person who did not ask?
   *
   * The field Phase 6 filters on. `cautions` says WHY a passage might be wrong
   * for someone and is good prose for Abigail to read; it fired on 30 of 30
   * sample passages, so it cannot rank anything. This discriminates.
   */
  handling?: "open" | "care" | "on-request-only";
  enrichmentModel?: string;
  enrichmentVersion?: number;
  enrichedAt?: Date;

  /** Raw passage text embedding. */
  embedding?: number[];
  embeddingModel?: string;
  /**
   * Enrichment + text embedding, kept ALONGSIDE the raw one rather than
   * replacing it, so the two can be measured against each other on the same
   * queries instead of the better one being assumed.
   */
  embeddingEnriched?: number[];
  embeddingEnrichedModel?: string;
  /** Exactly what was embedded into embeddingEnriched. Kept for auditability. */
  searchTextEnriched?: string;
  createdAt: Date;
  updatedAt: Date;
}

const passageSchema = new Schema<PassageDocument>(
  {
    reference: { type: String, required: true, trim: true },
    bookSlug: { type: String, required: true, trim: true, lowercase: true },
    authorId: { type: Schema.Types.ObjectId, ref: "Author", default: null },
    chapter: { type: Number, required: true, min: 1 },
    startVerse: { type: Number, required: true, min: 1 },
    endVerse: { type: Number, required: true, min: 1 },
    endChapter: { type: Number, required: true, min: 1 },
    texts: { type: Map, of: String, required: true, default: () => new Map() },
    themes: { type: [String], required: true, default: [] },
    stageSlugs: { type: [String], required: true, default: [] },
    situations: { type: [String], required: true, default: [] },
    // Not `required: true` with a "" default — Mongoose's `required` tests
    // truthiness, which would make the field unsatisfiable (CONVENTIONS.md §6).
    textualNote: { type: String, trim: true },
    searchText: { type: String },
    summary: { type: String, trim: true },
    cautions: { type: [String], default: undefined },
    handling: { type: String, enum: ["open", "care", "on-request-only"] },
    enrichmentModel: { type: String, trim: true },
    enrichmentVersion: { type: Number },
    enrichedAt: { type: Date },
    searchTextEnriched: { type: String },
    embeddingEnriched: { type: [Number], default: undefined },
    embeddingEnrichedModel: { type: String, trim: true },
    // `default: undefined` IS LOAD-BEARING. Mongoose gives every array path an
    // implicit `[]` default, so without this every unembedded passage is written
    // with `embedding: []` — and `{ embedding: { $exists: false } }`, which is
    // half the backfill's selector and the local retrieval filter, matches
    // NOTHING. The bug is invisible: the backfill still worked, because its
    // second clause (embeddingModel !== current) happened to catch everything,
    // and retrieval still returned results, because an empty vector scores 0.
    embedding: { type: [Number], default: undefined },
    embeddingModel: { type: String, trim: true },
  },
  { timestamps: true, versionKey: false },
);

// Segmentation is idempotent on this key: re-running it upserts the same
// pericope rather than duplicating it.
passageSchema.index({ reference: 1 }, { unique: true });
passageSchema.index({ bookSlug: 1, chapter: 1, startVerse: 1 });
passageSchema.index({ authorId: 1 });
// Retrieval filters (ARCHITECTURE.md §7: search_scripture takes stageSlug and
// situation). Multikey indexes on the array fields.
passageSchema.index({ stageSlugs: 1 });
passageSchema.index({ situations: 1 });
passageSchema.index({ themes: 1 });
// Backfill selector: find everything not embedded by the current model.
passageSchema.index({ embeddingModel: 1 });
passageSchema.index({ embeddingEnrichedModel: 1 });
// Backfill selector for enrichment.
passageSchema.index({ enrichmentModel: 1, enrichmentVersion: 1 });
// Phase 6 will filter on this on the hot path.
passageSchema.index({ handling: 1 });
// The keyword half of hybrid retrieval. A Mongo text index works both locally
// and on Atlas, which matters because the vector half does NOT — $vectorSearch
// is Atlas-only, and keyword search staying portable is what lets retrieval be
// exercised at all during development.
passageSchema.index({ searchText: "text" }, { name: "passage_text" });

// No soft-delete middleware on any corpus collection.
//
// THE OMIT LIST IS THE POINT. `embedding` is a multi-hundred-float array on the
// hottest read path in the app — every chapter the reader opens, every result
// search_scripture returns, every carrying revisited. Declared HERE rather than
// at a call site so every future serialization inherits it. See
// model-utils.applyApiTransforms and the Pepta /home incident it documents.
// `cautions` is deliberately omitted from the API shape for now: it is a signal
// FOR the retriever and for Phase 6, not copy for a reader. Surfacing "this
// passage would be the wrong thing to give you" in a client response is a
// product decision nobody has made yet.
applyApiTransforms(passageSchema, [
  "embedding",
  "embeddingModel",
  "embeddingEnriched",
  "embeddingEnrichedModel",
  "searchText",
  "searchTextEnriched",
  "cautions",
]);

export const PassageModel = mongoose.model<PassageDocument>(
  "Passage",
  passageSchema,
);
